#!/bin/bash
# =============================================================================
# makeModelFolders.sh
#
# Creates one OpenFOAM case folder per turbulence model from a base case.
# Each model folder is a complete, self-contained case ready to run.
#
# Usage:
#   bash makeModelFolders.sh [OPTIONS]
#
# Options:
#   -b, --base      PATH   Template case directory (default: ../meshIndependence/runs/familyII_4)
#   -o, --outdir    PATH   Output directory for model cases (default: ./runs)
#   -m, --models    LIST   Comma-separated models to create
#                          (default: fixed NASA TMR wall-resolved model set)
#   -a, --aoa       DEG    Angle of attack in degrees (default: 10)
#   -h, --help             Show this help message
#
# Default fixed NASA TMR wall-resolved models:
#   SpalartAllmaras  One-equation SA validation baseline
#   kOmegaSST        k-omega SST comparison
#   kOmega           Standard k-omega comparison
#
# Additional compatibility-test models, only run explicitly with --models:
#   kEpsilon         Standard k-epsilon
#   realizableKE     Realizable k-epsilon
#   RNGkEpsilon      RNG k-epsilon
#   LaunderSharmaKE  Low-Re k-epsilon
#
# Notes:
#   The k-epsilon-family models are not part of the default production sweep
#   on the fixed low-y+ NASA TMR mesh. They either diverged or produced
#   nonphysical force coefficients during smoke testing.
#
# Expected template case structure:
#   ../meshIndependence/runs/familyII_4/
#     0/
#       include/initialConditions
#       U, p, k, omega, epsilon, nut, nuTilda
#     constant/
#       transportProperties
#       turbulenceProperties    ← model is changed per run
#     system/
#       controlDict, fvSchemes, fvSolution
#
# Output:
#   runs/
#     SpalartAllmaras/
#     kOmegaSST/
#     kOmega/
#     ...  (additional folders only when requested with --models)
#
# =============================================================================

set -euo pipefail

# =============================================================================
# DEFAULTS
# =============================================================================
BASE_CASE="../meshIndependence/runs/familyII_4"
OUT_DIR="./runs"
AOA=10
MODELS_ARG=""

# Default production model set for the fixed NASA TMR wall-resolved mesh.
# These models passed smoke testing with physically reasonable startup forces.
DEFAULT_MODELS=(
    "SpalartAllmaras"
    "kOmegaSST"
    "kOmega"
)

# Additional models kept available for explicit compatibility/robustness tests.
# These are not generated by default on the fixed low-y+ NASA TMR mesh.
EXTRA_MODELS=(
    "kEpsilon"
    "realizableKE"
    "RNGkEpsilon"
    "LaunderSharmaKE"
)

ALL_MODELS=(
    "${DEFAULT_MODELS[@]}"
    "${EXTRA_MODELS[@]}"
)

# Fields required by each model. Implemented as a function instead of an
# associative array so the script works with macOS Bash 3.2.
required_fields_for_model() {
    case "$1" in
        kOmegaSST)       echo "k omega nut" ;;
        SpalartAllmaras) echo "nuTilda nut" ;;
        kEpsilon)        echo "k epsilon nut" ;;
        realizableKE)    echo "k epsilon nut" ;;
        RNGkEpsilon)     echo "k epsilon nut" ;;
        kOmega)          echo "k omega nut" ;;
        LaunderSharmaKE) echo "k epsilon nut" ;;
        *)               echo "" ;;
    esac
}

# =============================================================================
# COLOUR OUTPUT
# =============================================================================
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

log_info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
log_ok()      { echo -e "${GREEN}[OK]${NC}    $*"; }
log_warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $*"; }
log_section() { echo -e "\n${BOLD}${CYAN}══ $* ══${NC}"; }

# Portable in-place sed wrapper for macOS/BSD sed and Linux/GNU sed.
sed_inplace() {
    local expr="$1"
    local file="$2"
    if sed --version >/dev/null 2>&1; then
        sed -i "$expr" "$file"
    else
        sed -i '' "$expr" "$file"
    fi
}

# =============================================================================
# USAGE
# =============================================================================
usage() {
    sed -n '3,40p' "$0" | sed 's/^# \?//'
    exit 0
}

# =============================================================================
# ARGUMENT PARSING
# =============================================================================
while [[ $# -gt 0 ]]; do
    case "$1" in
        -b|--base)     BASE_CASE="$2"; shift 2 ;;
        -o|--outdir)   OUT_DIR="$2";   shift 2 ;;
        -m|--models)   MODELS_ARG="$2"; shift 2 ;;
        -a|--aoa)      AOA="$2";       shift 2 ;;
        -h|--help)     usage ;;
        *) log_error "Unknown option: $1"; usage ;;
    esac
done

# Build model list
if [[ -n "$MODELS_ARG" ]]; then
    IFS=',' read -ra MODELS <<< "$MODELS_ARG"
else
    MODELS=("${DEFAULT_MODELS[@]}")
fi

# =============================================================================
# HEADER
# =============================================================================
echo ""
echo -e "${BOLD}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║   NACA 0012 — Multi-Model Case Generator                ║${NC}"
echo -e "${BOLD}║   OpenFOAM 2412                                          ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""
log_info "Base case  : $BASE_CASE"
log_info "Output dir : $OUT_DIR"
log_info "AoA        : ${AOA}°"
log_info "Models     : ${MODELS[*]}"
echo ""

# =============================================================================
# PRE-FLIGHT CHECKS
# =============================================================================
log_section "PRE-FLIGHT CHECKS"

ERRORS=0

# ── Check 1: OpenFOAM environment ────────────────────────────────────────────
# This generator only copies/patches dictionaries, so OpenFOAM does not need to
# be sourced here. runSimulations.sh performs the runtime OpenFOAM checks later.
if [[ -z "${WM_PROJECT:-}" ]]; then
    log_warn "OpenFOAM environment not loaded. This is OK for folder generation."
    log_warn "Runtime checks will be performed by the cluster or local OpenFOAM runner."
else
    log_ok "OpenFOAM $WM_PROJECT_VERSION loaded (WM_PROJECT=$WM_PROJECT)"
fi

# ── Check 2: OpenFOAM version ────────────────────────────────────────────────
if [[ -n "${WM_PROJECT_VERSION:-}" ]]; then
    if [[ "$WM_PROJECT_VERSION" != "2412"* ]]; then
        log_warn "Expected OpenFOAM 2412, found $WM_PROJECT_VERSION."
        log_warn "Files are written for 2412 — minor version mismatch may be fine."
    else
        log_ok "Version 2412 confirmed"
    fi
fi

for util in python3 realpath sed cp rm grep perl; do
    if ! command -v "$util" &>/dev/null; then
        log_error "Required utility not found in PATH: $util"
        ERRORS=$((ERRORS+1))
    else
        log_ok "Utility found: $util"
    fi
done

# ── Check 3: simpleFoam availability ─────────────────────────────────────────
# simpleFoam is not required to generate folders on macOS. It is required only
# when the cases are run later with OpenFOAM.
if ! command -v simpleFoam &>/dev/null; then
    log_warn "simpleFoam not found in PATH. This is OK for folder generation."
else
    log_ok "simpleFoam found: $(which simpleFoam)"
fi

# ── Check 4: Base case directory ─────────────────────────────────────────────
if [[ ! -d "$BASE_CASE" ]]; then
    log_error "Base case directory not found: $BASE_CASE"
    log_error "Create it or pass --base PATH"
    ERRORS=$((ERRORS+1))
else
    log_ok "Base case directory exists: $BASE_CASE"
fi

# ── Check 5: Required base case subdirectories ───────────────────────────────
for subdir in "0" "constant" "system"; do
    if [[ ! -d "$BASE_CASE/$subdir" ]]; then
        log_error "Missing directory in base case: $BASE_CASE/$subdir"
        ERRORS=$((ERRORS+1))
    else
        log_ok "Found: $BASE_CASE/$subdir/"
    fi
done

# ── Check 6: Required system files ───────────────────────────────────────────
for sysfile in "controlDict" "fvSchemes" "fvSolution"; do
    if [[ ! -f "$BASE_CASE/system/$sysfile" ]]; then
        log_error "Missing system file: $BASE_CASE/system/$sysfile"
        ERRORS=$((ERRORS+1))
    else
        log_ok "Found: system/$sysfile"
    fi
done

# ── Check 7: Required constant files ─────────────────────────────────────────
for cfile in "transportProperties" "turbulenceProperties"; do
    if [[ ! -f "$BASE_CASE/constant/$cfile" ]]; then
        log_error "Missing constant file: $BASE_CASE/constant/$cfile"
        ERRORS=$((ERRORS+1))
    else
        log_ok "Found: constant/$cfile"
    fi
done

# ── Check 8: Required 0/ fields ──────────────────────────────────────────────
for field in "U" "p" "k" "omega" "epsilon" "nut" "nuTilda"; do
    if [[ ! -f "$BASE_CASE/0/$field" ]]; then
        log_error "Missing 0/ field: $BASE_CASE/0/$field"
        ERRORS=$((ERRORS+1))
    else
        log_ok "Found: 0/$field"
    fi
done

# ── Check 9: initialConditions include file ───────────────────────────────────
if [[ ! -f "$BASE_CASE/0/include/initialConditions" ]]; then
    log_error "Missing: $BASE_CASE/0/include/initialConditions"
    ERRORS=$((ERRORS+1))
else
    log_ok "Found: 0/include/initialConditions"
fi

# ── Check 9b: Initial conditions must use numeric active entries ─────────────
if [[ -f "$BASE_CASE/0/include/initialConditions" ]]; then
    if grep -v '^[[:space:]]*//' "$BASE_CASE/0/include/initialConditions" | grep -q '#calc\|#codeStream'; then
        log_error "0/include/initialConditions still contains active #calc/#codeStream entries."
        log_error "This workflow expects numeric AoA_rad, Ux, Uz, and flowVelocity values."
        ERRORS=$((ERRORS+1))
    else
        log_ok "initialConditions uses numeric active values; no active #calc/#codeStream found"
    fi
fi

# ── Check 10: polyMesh (mesh must exist in base) ─────────────────────────────
if [[ ! -d "$BASE_CASE/constant/polyMesh" ]]; then
    log_warn "No polyMesh found in $BASE_CASE/constant/"
    log_warn "Mesh must exist before running simulations."
    log_warn "Run plot3dToFoam or blockMesh inside the base case first."
    log_warn "Continuing — mesh will need to be present before runSimulations.sh"
else
    # Check mesh has required files
    for mfile in "points" "faces" "owner" "neighbour" "boundary"; do
        if [[ ! -f "$BASE_CASE/constant/polyMesh/$mfile" ]]; then
            log_warn "Mesh file missing: constant/polyMesh/$mfile"
        fi
    done
    MESH_CELLS=$(grep -c "^(" "$BASE_CASE/constant/polyMesh/owner" 2>/dev/null || echo "unknown")
    log_ok "polyMesh found in base case"
fi

# ── Check 10b: OpenFOAM 2412 fvSchemes compatibility ────────────────────────
if [[ -f "$BASE_CASE/system/fvSchemes" ]]; then
    if ! grep -q "div((nuEff\*dev2(T(grad(U)))))" "$BASE_CASE/system/fvSchemes"; then
        log_error "system/fvSchemes is missing: div((nuEff*dev2(T(grad(U)))))"
        log_error "OpenFOAM 2412 SpalartAllmaras requires this viscous-stress divergence entry."
        ERRORS=$((ERRORS+1))
    else
        log_ok "fvSchemes contains OpenFOAM 2412 nuEff*dev2 viscous-stress entry"
    fi
fi

# ── Check 11: AoA is a valid number ──────────────────────────────────────────
if ! [[ "$AOA" =~ ^-?[0-9]+(\.[0-9]+)?$ ]]; then
    log_error "AoA must be a number, got: $AOA"
    ERRORS=$((ERRORS+1))
else
    log_ok "AoA = ${AOA}° is valid"
fi

# ── Check 12: Model names are valid ──────────────────────────────────────────
for model in "${MODELS[@]}"; do
    if [[ -z "$(required_fields_for_model "$model")" ]]; then
        log_error "Unknown turbulence model: $model"
        log_error "Valid models: ${ALL_MODELS[*]}"
        ERRORS=$((ERRORS+1))
    else
        log_ok "Model valid: $model"
        case "$model" in
            kEpsilon|realizableKE|RNGkEpsilon|LaunderSharmaKE)
                log_warn "$model is an explicit compatibility-test model on this fixed NASA TMR low-y+ mesh."
                log_warn "It is not part of the default production sweep."
                ;;
        esac
    fi
done

# ── Abort if any hard errors ──────────────────────────────────────────────────
echo ""
if [[ $ERRORS -gt 0 ]]; then
    log_error "$ERRORS pre-flight check(s) failed. Fix above errors and re-run."
    exit 1
fi
log_ok "All pre-flight checks passed."

# =============================================================================
# COMPUTE AoA-DEPENDENT FREESTREAM AND FORCE DIRECTIONS
# Used to patch initialConditions and controlDict in each generated case.
# The template case uses numeric values instead of #calc for batch-run compatibility.
# =============================================================================
U_INF="51.48"
read -r AOA_RAD UX UZ LIFT_X LIFT_Z DRAG_X DRAG_Z < <(python3 - "$AOA" "$U_INF" <<'PY'
import math
import sys

aoa = float(sys.argv[1])
u_inf = float(sys.argv[2])
rad = math.radians(aoa)
print(rad, u_inf * math.cos(rad), u_inf * math.sin(rad), -math.sin(rad), math.cos(rad), math.cos(rad), math.sin(rad))
PY
)

# Format consistently for OpenFOAM dictionaries
AOA_RAD_FMT=$(printf "%.15f" "$AOA_RAD")
UX_FMT=$(printf "%.6f" "$UX")
UZ_FMT=$(printf "%.6f" "$UZ")
LIFT_X=$(printf "%.8f" "$LIFT_X")
LIFT_Z=$(printf "%.8f" "$LIFT_Z")
DRAG_X=$(printf "%.8f" "$DRAG_X")
DRAG_Z=$(printf "%.8f" "$DRAG_Z")

log_info "AoA=${AOA}°: flowVelocity=($UX_FMT 0 $UZ_FMT)"
log_info "AoA=${AOA}°: liftDir=($LIFT_X 0 $LIFT_Z)  dragDir=($DRAG_X 0 $DRAG_Z)"

# =============================================================================
# CREATE MODEL FOLDERS
# =============================================================================
log_section "CREATING MODEL FOLDERS"

mkdir -p "$OUT_DIR"
CREATED=0
SKIPPED=0

for MODEL in "${MODELS[@]}"; do

    CASE_DIR="$OUT_DIR/$MODEL"

    # ── Skip if already exists ────────────────────────────────────────────────
    if [[ -d "$CASE_DIR" ]]; then
        log_warn "Already exists, skipping: $CASE_DIR"
        log_warn "  Delete it manually to recreate: rm -rf $CASE_DIR"
        SKIPPED=$((SKIPPED+1))
        continue
    fi

    log_info "Creating: $CASE_DIR"

    # ── Copy entire base case ─────────────────────────────────────────────────
    cp -r "$BASE_CASE" "$CASE_DIR"

    # ── Remove runtime artifacts copied from the base case ───────────────────
    rm -rf "$CASE_DIR"/processor* \
           "$CASE_DIR"/postProcessing \
           "$CASE_DIR"/dynamicCode \
           "$CASE_DIR"/VTK \
           "$CASE_DIR"/sets \
           "$CASE_DIR"/surfaces
    rm -f "$CASE_DIR"/log.* "$CASE_DIR"/*.log
    rm -f "$CASE_DIR"/run_status*.txt
    for time_dir in "$CASE_DIR"/*; do
        [[ -d "$time_dir" ]] || continue
        time_name="$(basename "$time_dir")"
        [[ "$time_name" == "0" ]] && continue
        if [[ "$time_name" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
            rm -rf "$time_dir"
        fi
    done

    # ── Patch AoA-dependent numeric freestream values in initialConditions ───
    IC_FILE="$CASE_DIR/0/include/initialConditions"
    sed_inplace "s/^AoA[[:space:]].*/AoA             $AOA;/" "$IC_FILE"
    sed_inplace "s/^AoA_rad[[:space:]].*/AoA_rad         $AOA_RAD_FMT;/" "$IC_FILE"
    sed_inplace "s/^U_inf[[:space:]].*/U_inf           $U_INF;      \/\/ m\/s/" "$IC_FILE"
    sed_inplace "s/^Ux[[:space:]].*/Ux              $UX_FMT;/" "$IC_FILE"
    sed_inplace "s/^Uz[[:space:]].*/Uz              $UZ_FMT;/" "$IC_FILE"
    sed_inplace "s/^flowVelocity[[:space:]].*/flowVelocity    ($UX_FMT 0 $UZ_FMT);/" "$IC_FILE"
    sed_inplace "s/Docker workflow/batch workflow/g" "$IC_FILE"
    sed_inplace "s/Docker runtime/batch runtime/g" "$IC_FILE"

    # ── Patch turbulenceProperties — set correct RASModel ────────────────────
    TP_FILE="$CASE_DIR/constant/turbulenceProperties"

    if grep -q "^[[:space:]]*RASModel[[:space:]]" "$TP_FILE"; then
        sed_inplace "s/^[[:space:]]*RASModel[[:space:]].*/    RASModel        ${MODEL};/" "$TP_FILE"
    elif grep -q "^[[:space:]]*//[[:space:]]*RASModel[[:space:]]" "$TP_FILE"; then
        sed_inplace "0,/^[[:space:]]*\/\/[[:space:]]*RASModel[[:space:]].*/s//    RASModel        ${MODEL};/" "$TP_FILE"
    else
        log_error "No RASModel entry found in $TP_FILE"
        exit 1
    fi

    if ! grep -q "^[[:space:]]*RASModel[[:space:]]\+${MODEL};" "$TP_FILE"; then
        log_error "Failed to set RASModel ${MODEL} in $TP_FILE"
        exit 1
    fi

    # ── Patch liftDir / dragDir / UInf in controlDict ──────────────────────────
    CD_FILE="$CASE_DIR/system/controlDict"
    perl -0pi -e "s/liftDir\s+\([^)]*\);/liftDir         ($LIFT_X 0 $LIFT_Z);/g" "$CD_FILE"
    perl -0pi -e "s/dragDir\s+\([^)]*\);/dragDir         ($DRAG_X 0 $DRAG_Z);/g" "$CD_FILE"
    perl -0pi -e "s/UInf\s+\([^)]*\);/UInf            ($UX_FMT 0 $UZ_FMT);/g" "$CD_FILE"
    if ! grep -q "liftDir[[:space:]]\+($LIFT_X 0 $LIFT_Z);" "$CD_FILE"; then
        log_error "Failed to patch liftDir in $CD_FILE"
        exit 1
    fi
    if ! grep -q "dragDir[[:space:]]\+($DRAG_X 0 $DRAG_Z);" "$CD_FILE"; then
        log_error "Failed to patch dragDir in $CD_FILE"
        exit 1
    fi
    if ! grep -q "UInf[[:space:]]\+($UX_FMT 0 $UZ_FMT);" "$CD_FILE"; then
        log_error "Failed to patch UInf in $CD_FILE"
        exit 1
    fi

    # ── Write a case metadata file (used by runSimulations.sh) ───────────────
    cat > "$CASE_DIR/case_meta.txt" << EOF
model=${MODEL}
aoa=${AOA}
created=$(date -Iseconds)
base_case=$(realpath "$BASE_CASE")
required_fields=$(required_fields_for_model "$MODEL")
U_inf=${U_INF}
AoA_rad=${AOA_RAD_FMT}
Ux=${UX_FMT}
Uz=${UZ_FMT}
flowVelocity=(${UX_FMT} 0 ${UZ_FMT})
liftDir=(${LIFT_X} 0 ${LIFT_Z})
dragDir=(${DRAG_X} 0 ${DRAG_Z})
EOF

    # ── Model-specific wall BC adjustments ───────────────────────────────────
    # LaunderSharmaKE: low-Re k-eps needs zeroGradient on epsilon wall
    if [[ "$MODEL" == "LaunderSharmaKE" ]]; then
        EPS_FILE="$CASE_DIR/0/epsilon"
        sed_inplace 's/type[[:space:]]\+epsilonWallFunction;/type            zeroGradient;/' "$EPS_FILE"
        log_info "  LaunderSharmaKE: set epsilon wall BC to zeroGradient"
    fi

    # SpalartAllmaras: nut wall BC should be nutLowReWallFunction (already set)
    # kEpsilon/realizableKE/RNGkEpsilon: high-Re, check nut uses nutkWallFunction
    if [[ "$MODEL" == "kEpsilon" || "$MODEL" == "realizableKE" || "$MODEL" == "RNGkEpsilon" ]]; then
        NUT_FILE="$CASE_DIR/0/nut"
        # If using high-Re wall functions, nut needs nutkWallFunction
        # Check if the case mesh has y+ > 1 — we leave a note; user decides
        log_info "  $MODEL: uses high-Re wall functions."
        log_info "    If mesh has y+ > 30: change nut airfoil BC to nutkWallFunction"
        log_info "    If mesh has y+ < 1:  nutLowReWallFunction (already set) is fine"
    fi

    log_ok "Created: $CASE_DIR  [model=$MODEL, AoA=${AOA}°]"
    CREATED=$((CREATED+1))

done

# =============================================================================
# SUMMARY
# =============================================================================
log_section "SUMMARY"
echo ""
echo -e "  ${GREEN}Created : $CREATED case(s)${NC}"
echo -e "  ${YELLOW}Skipped : $SKIPPED case(s) (already existed)${NC}"
echo ""
echo -e "  Output directory: ${BOLD}$OUT_DIR/${NC}"
echo ""
echo -e "  Folder layout:"
for MODEL in "${MODELS[@]}"; do
    if [[ -d "$OUT_DIR/$MODEL" ]]; then
        echo -e "    ${GREEN}✓${NC}  $OUT_DIR/$MODEL/"
    else
        echo -e "    ${YELLOW}–${NC}  $OUT_DIR/$MODEL/  (skipped)"
    fi
done

echo ""
echo -e "  ${BOLD}Study definition:${NC}"
echo -e "    Fixed NASA TMR Family II level 4 wall-resolved mesh production sweep"
echo -e "    Default models: SpalartAllmaras, kOmegaSST, kOmega"
echo -e "    k-epsilon-family models remain available only via --models for compatibility tests."

echo ""
echo -e "  ${BOLD}Next step:${NC}"
echo -e "    1. Ensure mesh exists: constant/polyMesh/ in each case"
echo -e "       (the mesh is copied from ../meshIndependence/runs/familyII_4 by default)"
echo -e "    2. Run on cluster:"
echo -e "       ${CYAN}bash cluster/submit_model_chain.sh${NC}"
echo ""
